package com.example.nationapp;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    private RecyclerView recyclerView;
    private CountryAdapter countryAdapter;
    private ArrayList<CountryModel> countrymodel;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        getData();

        recyclerView = findViewById(R.id.recycleview);
        countryAdapter = new CountryAdapter(countrymodel);

        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(MainActivity.this);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(countryAdapter);
    }
    private void getData() {
        countrymodel = new ArrayList<>();
        countrymodel.add(new CountryModel("Amerika Serikat", R.drawable.usa_flag, "Ibukota : Washington D.C", "Amerika Serikat, disingkat dengan AS, atau United States of America, disingkat USA atau U.S.A. atau United States, disingkat US atau U.S., harfiah: \"Perserikatan Negara-Negara Bagian Amerika\"), atau secara umum dikenal dengan Amerika saja,adalah sebuah negara republik konstitusional federal yang terdiri dari lima puluh negara bagian dan sebuah distrik federal. Negara ini terletak di bagian tengah Amerika Utara, yang menjadi lokasi dari empat puluh lima negara bagian yang saling bersebelahan, Amerika Serikat diapit oleh Samudra Pasifik dan Atlantik di sebelah barat dan timur, berbatasan dengan Kanada di sebelah utara, dan Meksiko di sebelah selatan. Dua negara bagian lainnya, yaitu Alaska dan Hawaii, terletak terpisah dari dataran utama Amerika Serikat.\n" +
                "\n"+
                "Negara bagian Alaska terletak di sebelah ujung barat laut Amerika Utara, berbatasan dengan Kanada di sebelah timur dan Rusia di sebelah barat, yang dipisahkan oleh Selat Bering. Sedangkan negara bagian Hawaii adalah sebuah kepulauan yang berlokasi di Samudra Pasifik. Amerika Serikat juga memiliki beberapa teritori di Pasifik dan Karibia. Dengan luas wilayah 3,79  juta mil persegi (9,83 juta km²) dan jumlah penduduk sebanyak 341 juta jiwa, Amerika Serikat merupakan negara terluas ketiga di dunia, dan terbesar ketiga menurut jumlah penduduk."));

        countrymodel.add(new CountryModel("Argentina", R.drawable.argentina_flag, "Ibukota : Bueno Aires", "Argentina, nama resminya Republik Argentina, adalah sebuah negara di paro selatan dan tenggara anak-benua Amerika Selatan dan merupakan negara berbahasa Spanyol terbesar di dunia.\n" +
                "\n" +
                "Argentina meliputi wilayah seluas 2.780.400 kilometer persegi, yang menjadikannya sebagai negara terluas ke-2 di benua Amerika Selatan setelah Brasil, negara terluas ke-4 di benua Amerika, dan negara terluas ke-8 di dunia. Landas kontinennya, yang diakui oleh PBB pada tahun 2016, mencapai 6.581.500 km², menjadi salah satu yang terbesar di dunia, terbentang dari benua Amerika hingga Kutub Selatan di Antarktika, melalui Atlantik Selatan.\n" +
                "\n" +
                "Argentina mengambil bentuk pemerintahan republik, demokratis, perwakilan, dan federasi yang terdesentralisasi, yang sejak tahun 1994 dibagi-bagi menjadi 23 provinsi, dan satu kota otonom, yang berperan sebagai ibu kota federal, dan kota terbesar di negara ini, Buenos Aires yang juga sebagai salah satu metropolitan yang terpadat di dunia."));
        countrymodel.add(new CountryModel("Australia", R.drawable.australia_flag, "Ibukota : Canbera", "Australia, dengan nama resmi Commonwealth of Australia, adalah sebuah negara di belahan Bumi selatan yang terdiri dari daratan utama benua Australia, Pulau Tasmania, dan berbagai pulau kecil di Samudra Hindia, dan Samudra Pasifik. Negara-negara yang bertetangga dengannya adalah Indonesia, Timor Leste, dan Papua Nugini di utara; Kepulauan Solomon, Vanuatu, dan Kaledonia Baru di timur-laut; dan Selandia Baru di tenggara." +
                "\n" +
                "\n Australia Dengan wilayah seluas 7.617.930 kilometer persegi,yang mana adalah negara terbesar di Oseania dan terbesar keenam di dunia. Australia adalah benua berpenghuni yang paling tua, paling rata, dan paling kering, dengan tanah yang paling tidak subur. Australia adalah negara megadiversitas, dan ukurannya yang demikian luas telah menjadi ruang bagi berbagai macam lanskap dan iklim, dengan gurun di kawasan pedalaman, hutan hujan tropis di timurlaut, dan pegunungan di tenggara.\n" +
                "\n" +
                "Nenek moyang Aborigin Australia mulai berdatangan dari Asia Tenggara sekitar 65.000 tahun yang lalu, selama zaman es terakhir. Kira-kira 40.000 tahun sebelum pendudukan bangsa Eropa pada akhir abad ke-18, Australia telah dihuni oleh Aborigin.[19] Sesampainya melalui laut, mereka menetap di benua itu dan telah membentuk sekitar 250 kelompok bahasa yang berbeda pada saat pemukiman Eropa, mempertahankan beberapa tradisi seni dan agama yang paling lama dikenal di dunia."));
        countrymodel.add(new CountryModel("Brunei Darussalam", R.drawable.brunei_flag, "Ibukota : Bandar Segi Begawan", "Brunei, dengan nama formal Brunei Darussalam, adalah negara berdaulat di Asia Tenggara yang terletak di pantai utara pulau Kalimantan. Negara ini memiliki wilayah seluas 5.765 km² yang menempati pulau Kalimantan dengan garis pantai seluruhnya menyentuh Laut Tiongkok Selatan. Wilayahnya dipisahkan ke dalam negara bagian di Sarawak, Malaysia.\n" +
                "\n" +
                "Saat ini, Brunei memiliki Indeks Pembangunan Manusia tertinggi kedua di Asia Tenggara setelah Singapura, sehingga diklasifikasikan sebagai negara maju. Menurut Dana Moneter Internasional, Brunei memiliki produk domestik bruto per kapita terbesar kelima di dunia dalam keseimbangan kemampuan berbelanja. Sementara itu, Forbes menempatkan Brunei sebagai negara terkaya kelima dari 182 negara karena memiliki ladang minyak bumi dan gas alam yang luas. Selain itu, Brunei juga terkenal dengan kemakmurannya dan ketegasan dalam melaksanakan agama Islam, baik dalam bidang pemerintahan maupun kehidupan bermasyarakat. Pada tahun 2020, tercatat bahwa Brunei memiliki penduduk sebanyak 460,345 jiwa"));
        countrymodel.add(new CountryModel("Kanada", R.drawable.canada_flag, "Ibukota : Ottawa", "Kanada merupakan negara paling utara di wilayah Amerika Utara. Negara ini terdiri dari 10 provinsi dan 3 teritori, dengan menganut sistem desentralisasi. Kanada berdiri pada tahun 1867, setelah disahkannya undang-undang Konfederasi. Kantor Gubernur Jenderal, Perdana Menteri, serta parlemen nasional terletak di kota tersebut. Luas Kanada mencapai 9.970.610 km².\n" +
                "\n" +
                "Kanada merupakan monarki konstitusional, dengan pemerintahan yang berbentuk demokrasi parlementer federal. Raja Charles III menjadi kepala negara.\n" +
                "\n" +
                "Kanada menjadi salah satu negara dengan keragaman etnis dan multikultural yang paling beragam di dunia. Imigran di negara ini tergolong besar, jika dibandingkan negara lainnya. Selain itu, perekonomian Kanada menjadi terbesar kesepuluh di dunia. Sumber daya alam (yang berlimpah), dan jaringan perdagangan internasional menjadi tumpuan utama ekonomi negara ini. Hubungan yang panjang dengan Amerika Serikat memberikan dampak yang signifikan terhadap ekonomi dan budaya kedua negara."));
        countrymodel.add(new CountryModel("Prancis", R.drawable.france_flag, "Ibukota : Paris", "Prancis, dengan nama resmi Republik Prancis adalah sebuah negara dengan wilayah metropolitan yang terletak di Eropa Barat dan memiliki berbagai pulau dan wilayah seberang laut yang terletak di benua lain. Negara ini berbatasan dengan Belgia, Luksemburg, Jerman, Swiss, Italia, Monako, Andorra, dan Spanyol. Prancis terhubung dengan Britania Raya melalui Terowongan Channel, yang berada di bawah Selat Inggris.\n" +
                "\n" +
                "Negara metropolitan ini memanjang dari Laut Mediterania hingga Selat Inggris dan Laut Utara, dan dari Sungai Rhine hingga Samudra Atlantik. Orang Prancis sering menyebut Prancis Metropolitan sebagai \"L'Hexagone\" karena bentuk geometri wilayahnya yang menyerupai heksagon. Prancis adalah sebuah negara republik konstitusional. Ideologi utamanya tercantum dalam Deklarasi Hak Asasi Manusia dan Warga Negara dan Sekuler garis keras.\n" +
                "\n" +
                "Prancis telah menjadi salah satu kekuatan terbesar dunia sejak pertengahan abad ke-17. Pada abad ke-18 dan 19, Prancis memiliki salah satu imperium kolonial terbesar saat itu, membentang dari Afrika Barat hingga Asia Tenggara, memengaruhi budaya dan politik setempat. Prancis merupakan negara maju, dengan ekonomi terbesar keenam (PDB nominal) atau terbesar kedelapan (PPP) di dunia. Merupakan negara yang paling banyak dikunjungi di dunia, didatangi 82 juta turis asing per tahunnya"));
        countrymodel.add(new CountryModel("Jerman", R.drawable.germany_flag, "Ibukota : Berlin", "Jerman, secara resmi disebut sebagai Republik Federal Jerman adalah negara berbentuk federasi di Eropa. Negara ini memiliki posisi ekonomi dan politik yang sangat penting di Eropa maupun di dunia. Dengan luas 357.021 kilometer persegi dan jumlah penduduk sekitar 84 juta jiwa, negara dengan 16 negara bagian ini menjadi anggota kunci organisasi Uni Eropa (penduduk terbanyak), penghubung transportasi barang dan jasa antarnegara sekawasan, serta menjadi negara dengan penduduk imigran ketiga terbesar di dunia.\n" +
                "\n" +
                "Meskipun negara-bangsa Jerman modern baru terbentuk pada tahun 1871 seusai Perang Prancis-Prusia, satuan-satuan politik di wilayah ini telah lama memainkan posisi penting dalam era monarki di Eropa sejak penguasaan oleh Kekaisaran Romawi menjelang era modern (Masehi) hingga berakhirnya Perang Napoleon. Ketika Imperium Romawi Suci dibubarkan pada tahun 1806 akibat perpecahan yang ditimbulkan oleh perang Napoleon, telah tumbuh rasa satu kebangsaan sebagai masyarakat berbahasa yang sama (bahasa Jerman). Namun, negara modern yang terbentuk kemudian tidak sanggup menyatukan cita-cita kebangsaan itu karena Austria membentuk sekutu bersama Hungaria menjadi negara terpisah dari negara Jerman modern. Pada tahun 1949, Jerman, dengan wilayah yang jauh berkurang akibat dua perang besar di Eropa, terbagi menjadi dua negara terpisah: Jerman Barat[9] dan Jerman Timur. Pemisahan ini berakhir 3 Oktober 1990 (menjadi hari nasional Jerman sekarang) ketika Jerman Timur secara resmi menyatukan diri dengan Jerman Barat."));
        countrymodel.add(new CountryModel("Indonesia", R.drawable.indonesia_flag, "Ibukota : Jakarta", "Indonesia, dengan nama resmi Republik Indonesia,adalah sebuah negara kepulauan di Asia Tenggara yang dilintasi garis khatulistiwa dan berada di antara daratan benua Asia dan Oseania sehingga dikenal sebagai negara lintas benua, serta antara Samudra Pasifik dan Samudra Hindia.\n" +
                "\n" +
                "Indonesia merupakan negara terluas ke-14 sekaligus negara kepulauan terbesar di dunia dengan luas wilayah sebesar 1.904.569 km², serta negara dengan pulau terbanyak ke-6 di dunia, dengan jumlah 17.504 pulau Nama alternatif yang dipakai untuk kepulauan Indonesia disebut Nusantara.Selain itu, Indonesia juga menjadi negara berpenduduk terbanyak ke-4 di dunia dengan penduduk mencapai 277.749.853 jiwa pada tahun 2022,serta negara dengan penduduk beragama Islam terbanyak di dunia, dengan penganut lebih dari 238.875.159 jiwa atau sekitar 86,9%.Indonesia adalah negara multiras, multietnis, dan multikultural di dunia"));
        countrymodel.add(new CountryModel("Italia", R.drawable.italy_flag, "Ibukota : Roma", "Italia, resminya Republik Italia adalah sebuah negara kesatuan republik parlementer di Eropa Terletak di jantung Laut Mediterania. Italia berbatasan dengan Prancis, Swiss, Austria, Slovenia, San Marino dan Vatikan. Italia mencakup area seluas 301.338 km² (116.347 mi²), dan dipengaruhi oleh iklim sedang dan iklim mediterania. Dilihat dari bentuknya, peta Italia berbentuk seperti sepatu bot atau di Italia sering disebut lo Stivale.[11][12] Dengan jumlah penduduk mencapai 61 juta jiwa, Italia merupakan negara anggota Uni Eropa ketiga yang paling banyak penduduknya setelah Jerman dan Prancis.\n" +
                "\n" +
                "Sejak Era Klasik, Italia sudah dihuni oleh berbagai bangsa dan peradaban. Seperti Bangsa Fenisia, Kartago, dan orang-orang Yunani kuno yang mendirikan permukiman di selatan Italia, bangsa Etruskan dan Kelt mendiami tengah dan utara Italia, serta suku Italia Kuno dan bangsa Italic yang tersebar di seluruh Semenanjung Italia dan Insular Italia (Sardinia dan Sisilia). Suku Italic atau yang dikenal sebagai Orang Latin membentuk Kerajaan Romawi yang pada akhirnya kerajaan tersebut menjadi sebuah republik yang berhasil menaklukkan dan mengasimilasi peradaban terdekat lainnya. Roma akhirnya muncul sebagai kekuatan dominan di cekungan mediterania, berhasil menaklukkan sebagian besar dunia kuno dan menjadi pusat kebudayaan, politik dan keagamaan terkemuka di peradaban Barat. Peninggalan Kekaisaran Romawi tersebar luas dan dapat dilihat dalam saluran distribusi global hukum sipil, pemerintahan republik, Kekristenan dan tulisan Latin"));
        countrymodel.add(new CountryModel("Jepang", R.drawable.japan_flag, "Ibukota : Tokyo", "Jepang, adalah sebuah negara kesatuan yang bersistem parlementer dengan berbentuk monarki konstitusional dan juga negara kepulauan di Asia Timur. Luas daratan Jepang 378.000 km² dan letaknya di ujung barat Samudra Pasifik, di sebelah timur Laut Jepang, dan bersebelahan dengan Tiongkok, Korea Selatan, dan Rusia. Pulau-pulau paling utara berada di Laut Okhotsk dan wilayah paling selatan berupa kelompok pulau-pulau kecil di Laut Tiongkok Timur, tepatnya di sebelah selatan Okinawa yang berseberangan dengan Taiwan.\n" +
                "\n" +
                "Jepang terdiri dari 6.852 pulau dan menjadikannya sebagai negara kepulauan. Pulau-pulau utama dari utara ke selatan adalah Hokkaido, Honshu (pulau terbesar), Shikoku, dan Kyushu. Sekitar 97% wilayah daratan Jepang berada di keempat pulau terbesarnya. Sebagian besar pulau di Jepang bergunung-gunung, dan sebagian di antaranya merupakan gunung berapi. Gunung tertinggi di Jepang adalah Gunung Fuji yang merupakan sebuah gunung berapi. Penduduk Jepang berjumlah 128 juta jiwa, dan berada di peringkat ke-10 negara berpenduduk terbanyak di dunia. Tokyo secara de facto adalah ibu kota Jepang, dan berkedudukan sebagai sebuah prefektur. Tokyo Raya adalah sebutan untuk Tokyo dan beberapa kota yang berada di prefektur sekelilingnya. Sebagai daerah metropolitan terluas di dunia, Tokyo Raya berpenduduk lebih dari 30 juta orang dan menjadikan nya kota terpadat di dunia."));
        countrymodel.add(new CountryModel("Palestina", R.drawable.palestine_flag, "Ibukota : Yerusalem", "Palestina, dengan nama resmi Negara Palestina adalah negara yang berada di Asia Barat, antara Laut Tengah dan Sungai Yordan. Didirikan pada tanggal 15 November 1988 dan secara resmi diperintah oleh Organisasi Pembebasan Palestina (PLO), kelompok ini mengklaim Tepi Barat (termasuk Yerusalem Timur) dan Jalur Gaza sebagai wilayahnya, yang semuanya telah menjadi wilayah pendudukan Israel sejak Perang Enam Hari tahun 1967. Tepi Barat memiliki 165 daerah kantong Palestina yang sebagian berada di bawah kekuasaan Palestina, namun sisanya, termasuk 200 pemukiman Israel, berada di bawah kendali penuh Israel. Jalur Gaza diperintah oleh Mesir tetapi ditaklukkan oleh Israel pada tahun 1967. Israel memerintah wilayah tersebut hingga menarik diri pada tahun 2005. Hamas merebut kekuasaan di sana setelah memenangkan pemilihan legislatif Palestina tahun 2006. Jalur Gaza sejak itu diblokade oleh Israel dan Mesir.\n" +
                "\n" +
                "Luas total wilayah Palestina mencapai 6.025 kilometer persegi (km²) pada 2017. Angka itu terbagi menjadi wilayah West Bank alias Tepi Barat yang luasnya 5.660 km², serta Jalur Gaza 365 km². Sebagian besar negara di dunia termasuk anggota Organisasi Kerja Sama Islam, Liga Arab, Gerakan Non-Blok, Perhimpunan Bangsa-Bangsa Asia Tenggara, dan beberapa negara-negara bekas Uni Soviet telah mengakui keberadaan Palestina sebagai sebuah negara berdaulat. Wilayah Palestina saat ini terbagi menjadi dua entitas politik, yaitu wilayah pendudukan Israel dan Otoritas Nasional Palestina. Deklarasi Kemerdekaan Palestina dinyatakan pada 15 November 1988 di Aljir oleh Dewan Nasional Palestina dan Organisasi Pembebasan Palestina."));
        countrymodel.add(new CountryModel("Arab Saudi", R.drawable.saudiarabia_flag, "Ibukota : Riyadh", "Arab Saudi, secara resmi dikenal sebagai Kerajaan Arab Saudi adalah sebuah negara Arab di Asia Barat yang mencakup hampir keseluruhan wilayah Semenanjung Arab. Dengan luas wilayah sekitar 2.150.000 km² (830.000 sq mi), Arab Saudi secara geografis merupakan negara terbesar kelima di Asia dan kedua terbesar di Dunia Arab, setelah Aljazair. Arab Saudi berbatasan langsung dengan negara Yordania dan Irak di utara, Kuwait di timur laut, Qatar, Bahrain, dan Uni Emirat Arab di timur, Oman di tenggara, dan Yaman di bagian selatan. Negara ini terpisah dengan Palestina dan Mesir oleh Teluk Aqaba. Negara ini adalah satu-satunya negara yang memiliki dua pesisir penting, yakni Laut Merah dan Teluk Persia, dan sebagian besar wilayah Arab Saudi wilayahnya adalah kawasan gurun pasir.\n" +
                "\n" +
                "Wilayah Arab Saudi modern terdiri dari empat distrik bersejarah yang berbeda: Hijaz, Najd, sebagian Arabia Timur (Al-Ahsa) dan Arabia Selatan ('Asir). Kerajaan Arab Saudi didirikan pada 1932 oleh Ibnu Saud. Dia mempersatukan empat wilayah dalam serangkaian penaklukan yang dimulai pada 1902 dengan ibu kotanya di Riyadh, rumah asal keluarganya, Wangsa Saud. Arab Saudi sejak itu menjadi monarki absolut, di mana keputusan politik dibuat atas dasar konsultasi antara Raja, Dewan Menteri, dan elit tradisional negara yang mengawasi pemerintahan. Gerakan memurnikan kembali keagamaan dengan metode mengikuti salafus shalih digambarkan sebagai \"fitur utama budaya Saudi\", meskipun kekuatan pendirian agama telah terkikis secara signifikan pada tahun 2010-an hingga-sekarang [11] Dalam Hukum Dasarnya, Arab Saudi terus mendefinisikan dirinya sebagai negara Islam Arab yang berdaulat dengan Islam sebagai agama resminya, bahasa Arab sebagai bahasa resminya, dan Riyadh sebagai ibu kotanya."));
        countrymodel.add(new CountryModel("Korea Selatan", R.drawable.southkorean_flag, "Ibukota : Seoul", "Republik Korea atau lebih dikenal sebagai Korea Selatan, adalah sebuah negara di Asia Timur yang meliputi wilayah selatan Semenanjung Korea. Di sebelah utara, Korea Selatan berbatasan dengan Korea Utara, di mana keduanya bersatu sebagai sebuah negara hingga tahun 1948. Laut Kuning di sebelah barat, Jepang berada di seberang Laut Jepang, dan Selat Korea berada di bagian tenggara. Negara ini dikenal dengan nama Hanguk oleh penduduk Korea Selatan, dan disebut Nam Chosŏn (남조선) oleh orang Korea Utara. Ibu kota Korea Selatan adalah Seoul.\n" +
                "\n" +
                "Penemuan arkeologis menunjukkan bahwa Semenanjung Korea telah dihuni sejak Zaman Batu Tua. Sejarah Korea dimulai dari pembentukan Dinasti Gojoseon pada 2333 SM, oleh Dangun. Setelah penyatuan Tiga Kerajaan Korea di bawah Silla pada 668 M, Korea menjadi satu di bawah Dinasti Goryeo dan Dinasti Joseon, hingga akhir Kekaisaran Korea Raya pada 1910 karena dianeksasi oleh Jepang. Setelah dilakukan Pembagian Korea oleh Uni Soviet dan Amerika Serikat pada akhir Perang Dunia Kedua, wilayah Korea akhirnya terbagi menjadi dua."));
        countrymodel.add(new CountryModel("Spanyol", R.drawable.spain_flag, "Ibukota : Madrid", "Spanyol, secara resmi dikenal dengan sebutan Kerajaan Spanyol (Spanyol: Reino de España) adalah sebuah negara di Eropa barat daya yang bersama Portugal, terdapat di Semenanjung Iberia. Batas darat Spanyol dengan Eropa adalah Pegunungan Pirenia dengan Prancis dan Andorra. Wilayahnya terdiri dari kota Ceuta dan Melilla di Afrika Utara, Kepulauan Canary di Samudra Atlantik, dan berbagai pulau di Laut Tengah.\n" +
                "\n" +
                "Wilayah Spanyol juga termasuk Kepulauan Balearic di Mediterania, Kepulauan Canary di Samudera Atlantik lepas pantai Afrika, dan dua kota otonom di Afrika Utara, Ceuta dan Melilla, yang berbatasan Maroko, ditambah Alboran, Kepulauan Chafarinas, Alhucemas, Vélez de la Gomera dan pulau kecil lainnya termasuk Perejil. Selain itu, kota Llívia adalah eksklave Spanyol terletak di dalam wilayah Prancis. Dengan luas 505.992 kilometer persegi (195.365 mil persegi), Spanyol adalah negara terbesar kedua di Eropa Barat dan Uni Eropa dan negara terbesar kelima di Eropa."));
        countrymodel.add(new CountryModel("Turki", R.drawable.turkey_flag, "Ibukota : Ankara", "Turki, secara resmi bernama Republik Turki, adalah sebuah negara kesatuan dengan sistem presidensial di kawasan Eurasia. Wilayahnya terbentang dari Semenanjung Anatolia di Asia Barat Laut hingga daerah Balkan di Eropa Tenggara. Turki berbatasan dengan Laut Hitam di sebelah utara; Bulgaria di sebelah barat laut; Yunani dan Laut Aegea di sebelah barat; Georgia di timur laut; Armenia, Azerbaijan, dan Iran di sebelah timur; Irak dan Suriah di tenggara; dan Laut Mediterania di sebelah selatan. Laut Marmara yang merupakan bagian dari Turki digunakan untuk menandai batas wilayah benua Eropa dan benua Asia, sehingga Turki dikenal sebagai negara transkontinental.\n" +
                "\n" +
                "Bangsa Turki mulai bermigrasi ke daerah yang dinamakan Turkish pada abad ke-11. Proses migrasi ini semakin dipercepat setelah kemenangan Kesultanan Seljuk melawan Kekaisaran Bizantium pada pertempuran Manzikert. Beberapa Beylik (Emirat Turki) dan Kesultanan Seljuk Rûm memerintah Anatolia sampai dengan invasi Kekaisaran Mongol. Mulai abad ke-13, beylik-beylik Ottoman menyatukan Anatolia dan membentuk kekaisaran yang daerahnya merambah sebagian besar Eropa Tenggara, Asia Barat, dan Afrika Utara. Setelah Kesultanan Utsmaniyah runtuh setelah kalah pada Perang Dunia I dan masalah internal (pemberontakan Gerakan Turki Muda dan Pemberontak bangsa Arab) sebagian wilayahnya diduduki oleh para Sekutu yang memenangi Perang Dunia I. Mustafa Kemal Atatürk kemudian mengorganisasikan gerakan perlawanan melawan Sekutu. Pada tahun 1923, gerakan perlawanan ini berhasil mendirikan Republik Turki Modern dengan Mustafa Kemal Atatürk menjabat sebagai presiden pertamanya."));

    }
}